language: python

sudo: false

python:
  - 3.5.2

services:
  - redis-server

install:
  - pip install -r requirements-dev.txt

script:
  - python setup.py test --coverage -q
  - flake8
  - python setup.py test --coveralls

notifications:
  email: false
